export const PLAYER_THUMB_BASE_URL = process.env.NEXT_PUBLIC_SLEEPER_PLAYER_THUMB_BASE_URL;
export const PLAYER_BASE_URL = process.env.NEXT_PUBLIC_SLEEPER_PLAYER_BASE_URL;
export const LEAGUE_ID = process.env.NEXT_PUBLIC_LEAGUE_ID;
export const SERVER_URL = process.env.NEXT_PUBLIC_SERVER_URL;
export const SLEEPER_AVATAR_BASE_URL = process.env.NEXT_PUBLIC_SLEEPER_AVATAR_BASE_URL;
export const SLEEPER_AVATAR_THMUB_BASE_URL = process.env.NEXT_PUBLIC_SLEEPER_AVATAR_THUMB_BASE_URL;