import * as Interfaces from "@/interfaces";

export const initPlayer: Interfaces.Player = {
    first_name: '',
    team: '',
    position: '',
    age: 0,
    birth_date: "",
    cbs_id: "",
    college: "",
    depth_chart_order: 0,
    espn_id: 0,
    fantasy_data_id: 0,
    full_name: "",
    height: "",
    high_school: "",
    last_name: "",
    number: 0,
    player_id: "",
    rotowire_id: 0,
    sportradar_id: "",
    weight: "",
    yahoo_id: 0,
    years_exp: 0,
    fantasy_calc_id: "",
    mfl_id: "",
    ktc: {
        value: 0,
        rank: "",
        tier: "",
        trend: "",
        path: "",
        positionRank: "",
    },
    sf: {
        value: 0,
        rank: "",
        tier: "",
        trend: "",
        path: "",
        positionRank: "",
    },
    fc: {
        value: 0,
        rank: "",
        tier: "",
        trend: "",
        path: "",
        positionRank: "",
    },
    dp: {
        value: 0,
        rank: "",
        tier: "",
        trend: "",
        path: "",
        positionRank: "",
    },
    fantasy_pro: {
        fantasypros_id: "",
        rank: "",
        ecr: "",
        sd: "",
        best: "",
        worst: "",
        player_page_url: "",
        player_image_url: "",
        player_bye_week: "",
        player_owned_avg: "",
        player_owned_espn: "",
        player_owned_yahoo: "",
        player_opponent: "",
        player_opponent_id: "",
        player_ecr_delta: "",
        pos_rank: "",
        start_sit_grade: "",
        r2p_pts: "",
    },
    injury_status: ""
};