"use client";
import "@/styles/globals.css";
import styles from "./Dashboard.module.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google"
import { 
  LeagueProvider,  
  PlayerProvider,
  FantasyCalcProvider,
  KTCProvider,
  DynastyProcessProvider,
  FantasyProProvider,
  FantasyMarketProvider,
  useLeagueContext,
} from "@/context";
import * as Interfaces from "@/interfaces";
import LeagueNav from "@/components/navigation/LeagueNav";
import SideNavBar from "@/components/navigation/SideNavBar";
import { useState } from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DynastyHub',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: Interfaces.ChildrenProps) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <LeagueProvider>
          <PlayerProvider>
            <FantasyCalcProvider>
              <KTCProvider>
                  <DynastyProcessProvider>
                    <FantasyProProvider>
                      <FantasyMarketProvider>
                        <LeagueNav isSidebarOpen={isSidebarOpen} setIsSidebarOpen={setIsSidebarOpen}/>
                        <div className={styles.dashboardLayout}>
                          <SideNavBar isSidebarOpen={isSidebarOpen}/>
                          <div className={styles.dashboardContent}>
                            {children}
                          </div>
                        </div>
                      </FantasyMarketProvider>
                    </FantasyProProvider>
                  </DynastyProcessProvider>
              </KTCProvider>
            </FantasyCalcProvider>
          </PlayerProvider>
        </LeagueProvider>
      </body>
    </html>
  )
}
