import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google"
import { LeagueProvider } from "@/context/sleeper/LeagueContext";
import { MatchProvider } from "@/context/sleeper/MatchContext";
import { OwnerProvider } from "@/context/sleeper/OwnerContext";
import { PlayerProvider } from "@/context/sleeper/PlayerContext";
import { ChildrenProps } from "@/interfaces";
import DashboardLayout from "@/layouts/Dashboard";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DynastyHub',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: ChildrenProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LeagueProvider>
          <MatchProvider>
            <OwnerProvider>
              <PlayerProvider>
                <DashboardLayout>{children}</DashboardLayout>
              </PlayerProvider>
            </OwnerProvider>
          </MatchProvider>
        </LeagueProvider>
      </body>
    </html>
  )
}
